{
 "title": "RealTime_Cryptocurrency",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "BNB Prices",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT (bn_last*thb_usdt) as binance, bk_last as bitkub, cast(timestamp AS timestamp) ts \r\nFROM 'topic_Binance_Bitkub' WHERE currency='BNB' ORDER BY ts DESC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Binance USD",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT bn_last, cast(timestamp AS timestamp) ts FROM 'topic_Binance_Bitkub' WHERE currency='BNB' ORDER BY ts DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "PercentChange",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT bn_percentChange, bk_percentChange, cast(timestamp AS timestamp) ts FROM 'topic_Binance_Bitkub' WHERE currency='BNB' ORDER BY ts DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Bitkub THB",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT bk_last, cast(timestamp AS timestamp) ts FROM 'topic_Binance_Bitkub' WHERE currency='BNB' ORDER BY ts DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Binance Order Prices",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT bn_lowAsk as high, bn_last as close, bn_highBid as low, cast(timestamp AS timestamp) ts FROM 'topic_Binance_Bitkub' WHERE currency='BNB' ORDER BY ts DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Bitkub Order Prices",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT bk_lowAsk as high, bk_last as close, bk_highBid as low, cast(timestamp AS timestamp) ts FROM 'topic_Binance_Bitkub' WHERE currency='BNB' ORDER BY ts DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "ThaiBath/USDT",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT thb_usdt, cast(timestamp AS timestamp) ts FROM 'topic_Binance_Bitkub' WHERE currency='BNB' ORDER BY ts DESC LIMIT 1\n"
    }
   ]
  }
 ]
}